apiVersion: v1
kind: Pod
metadata:
  name: log-writer
spec:
  containers:
  - name: logger
    image: busybox
    command: ["/bin/sh", "-c"]
    args: ["while true; do echo '📄 Logging from pod at $(date)' >> /mnt/app-logs/log.txt; sleep 5; done"]
    volumeMounts:
    - mountPath: /mnt/app-logs
      name: log-volume
  volumes:
  - name: log-volume
    persistentVolumeClaim:
      claimName: app-logs-pvc
