---
- name: Install and configure Nginx web server
  hosts: managed
  become: true

  tasks:
    - name: Install Nginx
      ansible.builtin.yum:
        name: nginx
        state: present

    - name: Ensure Nginx is running and enabled
      ansible.builtin.service:
        name: nginx
        state: started
        enabled: true

    - name: Customize the index.html page
      ansible.builtin.copy:
        content: "<h1>Welcome from Mohamed's Ansible Playbook 🚀</h1>"
        dest: /usr/share/nginx/html/index.html
