apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-storage-mysql-0
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: standard
  resources:
    requests:
      storage: 1Gi

