version: '3.8'

services:
  db:
    image: mysql:5.7
    restart: always
    env_file:
      - .env
    volumes:
      - ./db_data:/var/lib/mysql
      - ./mysql-init:/docker-entrypoint-initdb.d
    networks:
      - app-network

  app:
    build: ./app
    restart: always
    ports:
      - "3000:3000"
    env_file:
      - .env
    depends_on:
      - db
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
